### PR TITLE
Merge remote-tracking branch 'autobuild/master' into HEAD

### PR DESCRIPTION
**Pull request by Rauldg**
@arneboe, Let me check that it builds with all the Entern stack before merging

### CODE REVIEW

**Comment by chhtz** [comment]
Instead of back-porting changes from master, could we try to migrate Entern back to master? Perhaps after https://github.com/rock-core/base-types/pull/120 (minus the IMO obsolete change in `Trajectory.hpp`).

My student recently had problems building Entern due to this fork, which could be resolved by switching back to the master (yes, I should just create a smaller simpler project for what he is doing ...)

**Comment by jmachowinski** [comment]
What about about simply rebase onto master ?

**Comment by Rauldg** [comment]
@chhtz I don't know what the changes affect, because I didn't introduce them and I didn't as well develop the libraries that use those changes. Can you check from your side whatever gets affected by those changes? I think @arneboe could also check if it is possible to remove those changes.

@jmachowinski rebasing would also be fine for now, not much different to this merge. I decided for merging because apparently the changes that we propose are [not acceptable for the base types maintainers](https://github.com/rock-core/base-types/pull/120), but anyway rebase might be indeed better for readability of the history.

@chhtz I am working on getting the entern stack, currently on [branch of the buildconf](https://git.hb.dfki.de/entern/buildconf/blob/vulcano2019/init.rb), until I find a nice solution. If your student is still trying, let me know so we can coordinate.

**Comment by Rauldg** [comment]
By the way, this MR does not work because some patch that is applied by autoproj is not matching anymore. Before merging, this should be fixed at least. I can take care of this patch fix but it would be nice indeed if we can get rid of this fork.

**Comment by Rauldg** [comment]
@chhtz @jmachowinski  the issue I mentioned above with respect to the patch has been fixed, can this be merged?

**Comment by chhtz** [comment]
I don't mind whether you merge or rebase this. And I'm not updating that frequently anyway. So feel free to do what you think is best.

**Comment by Rauldg** [comment]
> I don't mind whether you merge or rebase this. And I'm not updating that frequently anyway. So feel free to do what you think is best.

@chhtz  I don't have the permissions to merge, If you are OK with the changes, please merge. Or Provide me the permissions that would allow me to merge the update myself. Thanks!

**Pull request merged**
